# ustawienie strony
lang: pl
locale: pl

title: Marek Tymowski - pisarz amator, copywriter
description: Marek Tymowski - pisarz amator, copywriter. Marek Tymowski to specjalista SEO ze świeżym podejściem do marketingu sieciowego oraz reklam na stronach internetowych.

url:
baseurl:

favicon: favicon.png

# autor
autor:
  name: Marek Tymowski
  email: kontakt@tymowski.tk
  url:
  avatar: /assets/img/ja2.webp

# Build settings
markdown: kramdown

social_link:
  twitter: mediatym
  facebook: mediatym
  instagram: mediatym
  linkedin:
  slideshare:
  githab:

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  # - jemoji #Odkomentuj to, aby zezwolić na używanie emoji w swoim poście

# paginacja dla index.html
paginate: 3
paginate_path: "/blog/page/:num/"
#paginate_path: "/blog/page:num/"

# paginacja dla blog.html
#pagination:
#  enabled: true
#  per_page: 3 # Liczba postów na stronie
#  permalink: /blog/page/:num/ # Ścieżka do kolejnych stron
#  collection: posts # Kolekcja postów
# layout: blog # Layout do użycia na stronach z paginacją

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:title/"

  #- scope:
  #    path: "pages/blog.md"
  #  values:
  #    layout: "blog"
  #    pagination: enabled

collections:
  pages:
    output: true
    permalink: /:name/

exclude:
  - README.md
  - CNAME
  - package.json
  - .gitignore
  - LICENSE
